### ISSUE TITLE
GEM v2 water and final mask issue

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#28]
Module 1 runs great!  The only issue I've encountered is that the Water Mask and Final Mask don't fully load in the viewer, this is replicated in the downloads which I've loaded into QGIS and are also incomplete.  You can see the north of the ROI is missing.  Please could you investigate?  The topo mask looks fine by the way

![image](https://github.com/user-attachments/assets/7bc3c761-6897-478c-bd0f-86f3f8804e71)

![image](https://github.com/user-attachments/assets/745e4a91-a635-45c6-84a3-04d4a79dd555)

**Comment by zibnix** [comment]
Hi Sam,

Not sure what's going on there, but maybe just a genuine lack of imagery for the range used? Here's what the final mask looks like from v2 when I run it using the following:

Contemporary:  2022-2022 months: 5-10
Historical: 2019-2019 months: 5-10

cloud cover: 15
min_avg: 0.5

![Vel_S2](https://github.com/user-attachments/assets/30d10787-4ab0-49bf-ac80-4f55285b529a)

Maybe some parameters are different between your run and mine, can you send those to me and I can look again?

Thanks!

**Comment by thejollygeo** [comment]
Ahh it is due to a lack of imagery!  I've just remembered that the water mask is produced using a different MNDWI min_avg, so even though the 4 composites are complete, some of the images used to make these have been filtered out when producing the water mask.
Resulting in the following popping up in the Console:
No. Contemporary Low-Tide Images for Water Mask: **1**
No. Historic Low-Tide Images for Water Mask: 8

I've widened the contemporary months window from 9-9 to 8-10, solving the issue and resulting in:
No. Contemporary Low-Tide Images for Water Mask: **4**
No. Historic Low-Tide Images for Water Mask: 8

Could you add a line at the bottom of Mod 1 Section 5 that says something like:
_If your water mask and final mask are incomplete, review above the number of contemporary and historical low-tide images available for the water mask (there needs to be enough images to cover your entire ROI).  If not enough, widen the months and/or years windows to filter in more imagery._

![image](https://github.com/user-attachments/assets/03061be6-5c0e-4f27-be7e-3032a7929634)

Incidentally the file size of the images means loading them into GIS is more challenging (though still doable) - I will have to investigate this further, possibly with the help of this year's MGEM students!
