### ISSUE TITLE
GMW v4 now available in Awesome GEE

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#29]
Building on previous improvements where known historical mg extents (from Giri MFW and GMW 1996-2020 maps) were combined to produce a better 'known mangrove extent':

The new GMW v4 data has now been added to Awesome GEE
https://gee-community-catalog.org/projects/mangrove/

The 2020 map has much been improved by using smaller S2 pixels vs the old 2020 map:
_Using Copernicus Sentinel-2 satellite imagery, processed to a pixel resolution of 10 m, the mangrove extent has been completely remapped and revised with many areas which were not previously mapped now included within the new map._

TAB comparisons are documented [here](https://docs.google.com/spreadsheets/d/1HR4enIfeLzJdXLwl6XarkRvDTEUzEARi5PZUWZay9TQ/edit?gid=0#gid=0) for each improvement we implement, once this new data is incorporated I will add the comparison - will be interesting to see.

**_Just a thought: it may be that the code referring to the updated data remains the same as before, so no changes needed?!_**

**Comment by zibnix** [comment]
Unfortunately it is not a zero code change, as the union dataset has not been updated to include the new 2020 10m data, but it is easy enough to combine them in GEE!

**Comment by zibnix** [comment]
fixed in https://github.com/Blue-Ventures-Conservation/GEM/commit/963c2b47e803911affe4c30ab79fad2049e5a111

**Comment by thejollygeo** [comment]
Thanks I can see in the code that this means we now have two 2020 layers within the union.  Although this is less scientifically valid, practically this means GEM is more conservative when creating an ROI given the old + new 2020 layer will mean more areas are included as 'known mangrove' - so I think this is fine!
