### ISSUE TITLE
Section 3: Prepare Imagery for Processing

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#37]
Ran this step multiple times for ICF site Kubu Raya, Indonesia.  I'm experiencing lots of errors, is this likely to be due to throttling by Google?  If so I'll prioritise sending them an email (and this is further evidence of the issues we are experiencing)

1st time: took 6 mins to return numbers of images found
2nd time: took 6 mins
3rd time: returned an error
![image](https://github.com/user-attachments/assets/b608a22e-e971-4940-a5c3-ea032184e874)

4th time: returned a different error
![image](https://github.com/user-attachments/assets/bb11b813-11bc-47ad-bcdc-51344c17f88d)

**Comment by thejollygeo** [comment]
Ok another hour of trying to use v2 GEM and it is clear there is some sort of throttling going on.  When using Sentinel-2 imagery everything takes **so long**, I even had to wait 5+ mins for the composite tiles to start showing having clicked `Add Contemporary Imagery`

I'll draft up an email and would be great to get your eyes on it before I send

**Comment by zibnix** [comment]
Weird, yeah with that reasonable number of images, I wouldn't expect this to time out. I'll have another look at the sentinel desktop stuff tomorrow.

**Comment by thejollygeo** [comment]
![image](https://github.com/user-attachments/assets/62d6514b-6b88-4bf2-816b-7e0f0a1edcaa)
Also getting loads of these errors when loading composite tiles

**Comment by zibnix** [comment]
I think this is going to end up being similar to the issue with the buffers in #36, which has to do with the coastline just being too complex, and our attempts at simplifying it not working properly. Hopefully a fix there will help here as well.

**Comment by zibnix** [comment]
Yes, I believe this is now fixed along with #36. Simplifying the coastline is working and these images are returned much more quickly.

**Comment by thejollygeo** [comment]
Yes, huge improvement!
